baseurl = "/"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Rajekevin"
googleAnalytics = "XXX"
disqusShortname = "XXX"
pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Rajekevin"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    title = "toto"
    headline = "<? My BEAR IS YELLOW />"
    description = "Hello, I'm Rajekevin, a web developper. \n Every programmers can bring variables to life. I started writting my first variable in PHP calling $MyBearIsYellow. Since that the idea üí° of ‚Äã‚Äãsharing my knowledge  in computer science has been on my mind."
    github = "https://github.com/rajekevin"
    linkedin = "https://linkedin.com/in/rajekevin/"
    twitter = "https://twitter.com/iamrkvin"
    email = "rajekevin@hotmail.fr"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[Permalinks]
    post = "/:filename/"

[[menu.main]]
    name = "Home üè†"
    url = "/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
